# Nome do workflow para fácil identificação no GitHub Actions
name: Run Python Script  

# Define os eventos que acionam o workflow
on:  
  push:  # Quando houver um "push" (envio de código)
    branches:  
      - main  # Executa o workflow somente quando o push for na branch 'main'
  workflow_dispatch:  # Permite execução manual do workflow na interface do GitHub

# Definindo os trabalhos que serão executados no workflow
jobs:  
  run-python-script:  # Nome do trabalho para fácil referência
    runs-on: ubuntu-latest  # Define o ambiente onde o trabalho será executado (Ubuntu mais recente)

    # Definindo os passos para o trabalho
    steps:  
      # Primeiro passo: fazer o checkout do repositório
      - name: Check out the repository  # Nome do passo, para clonar o repositório na máquina virtual
        uses: actions/checkout@v3  # Utiliza uma ação do GitHub para clonar o código do repositório

      # Segundo passo: configurar o Python
      - name: Set up Python  # Nome do passo, configurando o ambiente Python
        uses: actions/setup-python@v4  # Utiliza uma ação do GitHub para instalar e configurar o Python
        with:  
          python-version: '3.x'  # Especifica a versão do Python (qualquer versão 3.x, por exemplo, '3.9')

      # Terceiro passo: instalar as dependências do projeto
      - name: Install dependencies  # Nome do passo, instalando as bibliotecas necessárias
        run: |  
          python -m pip install --upgrade pip  # Atualiza o gerenciador de pacotes pip para a última versão
          pip install -r requirements.txt  # Instala todas as dependências especificadas no arquivo requirements.txt

      # Quarto passo: executar o script Python
      - name: Run Python Script  # Nome do passo, indicando que o script Python será executado
        run: |  
          python server.py  # Executa o script principal 'server.py'
